public class Comentarios() {
    public static void main(String[] args) {
        //Um comentário de uma única linha.

        /*Comentário multiline, você pode comentar em várias linhas*/
    }

    public void metodo() {
        /** 
         * Estas duas estrelinhas acima
         * é para identificar que você
         * pretende elaborar um comentário
         * a nível de documentação.
         * Que incrível !!!
         */
    }
}